title: ""
labels: ["Notebook Submission"]
body:
  - type: markdown
    attributes:
      value: |
        This is text that will show up in the template!
  - type: input
    id: user
    attributes:
      label: User
      description: Github user name
    validations:
      required: true
  - type: input
    id: repo
    attributes:
      label: Repo
      description: Github repository name
    validations:
      required: true
  - type: input
    id: path
    attributes:
      label: Path
      description: Path of the .jsnb file within the github repo. Should be line `example_folder/example_file.jsnb`
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Description of notebook

  - type: dropdown
    id: download
    attributes:
      label: Which domain is the notebook for?
      options:
        - AI/ML
        - JavaScript
        - XR
        - Gaming
        - Others
    validations:
      required: false

